### ISSUE TITLE
求助，我的绳网一直在加载中

### ISSUE THREAD

**Issue by cold-heart-314** [share121/inter-knot#1125]
![6b5ce225997c094611f263ec7a4bfe8](https://github.com/user-attachments/assets/f55f5fa1-e01e-4897-9e5a-2a662c01c439)

**Comment by cold-heart-314** [comment]
在github里发帖和看帖都行，应该不是网速问题

**Comment by share121** [comment]
可能是你的“绳网跨域助手”脚本过旧，访问 https://greasyfork.org/zh-CN/scripts/502874 安装最新版
