### ISSUE TITLE
灌个水

### ISSUE THREAD

**Issue by sunnycherry2023** [share121/inter-knot#1290]
灌个水
直接访问
interknot.work
即可到达
https://github.com/share121/inter-knot/discussions/1269

_Originally posted by @sunnycherry2023 in https://github.com/share121/inter-knot/discussions/1195#discussioncomment-10301711_

**Comment by InterKnotGuard** [comment]
issues部分是对项目开发和反馈的地方，请不要在issue页面上发无关紧要的内容，谢谢！
