### ISSUE TITLE
[Feature]使用Waline管理评论和帖子

### ISSUE THREAD

**Issue by Buer-Nahida** [share121/inter-knot#1414]
# Q: 为什么我要提出这个Issue

绳网跨域助手+Github的管理方式很有局限性：

1. 由于是Github Discussions提供的发帖方式，管理方式都得跟着Github走，且有可能因为滥用资源被封（参考https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/issues/603
）
2. 发帖人无法删帖（原因同上）
3. Github在国内的半墙状态和手机浏览器没几个支持插件导致很多想上绳网的用户被拦在外边（或许是好处？）
4. 访问速度慢（原因同第一条）

## Q: 什么是Waline

[Waline](https://waline.js.org)是一款一款简洁、安全的评论系统，支持发送图片的操作，且Vercel（负责前端和评论系统）+TiDB（负责Waline数据库）这个部署方式完全免费（TiDB应该是超过多少数据后收费，毕竟数据中心的开销是一个巨大的数字）

[我的个人网站](https://naxida.me)使用了这个评论系统，所以我体会过它的部署难度，它部署起来很简单。

虽然Waline基本被用于博客的评论系统，但它支持发送图片，也支持回复，所以可以把每个评论归类为一条帖子

优点：
- 本地部署，不被Github牵着鼻子走
- 没有10M图片的限制
- 不怕被封
- Vercel和TiDB免费提供域名
- 用户登录门槛低，不用再找魔法、安装油猴插件、安装油猴脚本了
- 速度或许会快一点

缺点：
- 部署方式虽简单，但相关代码的修改是一大工程
- 可能会让更多的小鬼进来污染环境
- ***可能***不支持视频

## Q: 我可以贡献这个功能吗？

我不能贡献一个写好的功能，因为Waline***需要您自己部署***，况且我还是刚入门前端的萌新，而且我是个***初二***的学生，开学后就***初三***了，所以我***没有时间***把代码写好创建一个Pull request来把代码提交上去，但我可以参与贡献。

**Comment by Buer-Nahida** [comment]
> 好像有说法，入门门槛问题迟早是要解决的，要不可以先搞个内网测试一下？！

我自己吗？可我没时间啊，还有不到一个月我就开学了，初三一年几乎没有时间搞这东西

**Comment by zdxiaoda** [comment]
但是由于用户登录门槛低且没有 Github 账号作为门槛，会大大增大评论被自动程序爆破的风险。
如果增加人机验证，速率限制等防护措施又会增大不必要的工作量。
且现有的直接使用 Github 的方式不需要用户和管理员为上传图片进行额外操作。
个人感觉不用更换🤔

**Comment by Wynn-Zeng** [comment]
个人感觉可以学一下Giscus的原理，跳转之类的还是太麻烦了
关于GitHub账号作为门槛这个我狠狠支持

**Comment by VacuolePaoo** [comment]
现在能够实现论坛功能是最主要的，也看得出UI不是很细节，之后会改进的

**Comment by HKLHaoBin** [comment]
最大的问题是安全性，目前就是直接用的 github 的社区规则，那么很多安全性的问题就不需要开发者考虑，如果另外部署一个评论系统的话，就要付出非常多的努力去维护这个安全性，而且虽然 github 没办法删自己的帖（我不清楚开发者能不能删）但是可以改。

![Clip_2024-08-18_01-46-15](https://github.com/user-attachments/assets/9b66909f-bc29-4b12-835c-7e6783891173)

**Comment by 1ctrl-cv** [comment]
佬，友链dd
