### ISSUE TITLE
在新域名“绳网.top”中脚本失效

### ISSUE THREAD

**Issue by match-fire** [share121/inter-knot#1466]
如题
如果是我的问题，那我就关掉Issues

**Comment by match-fire** [comment]
解决方案：
将脚本第七行“// @match        https://xn--5o0anh.top/*”
换成// @match        https://www.xn--5o0anh.top/*
报错原因：粗心少了个www

**Comment by match-fire** [comment]
@share121

**Comment by match-fire** [comment]
@VacuolePaoo

**Comment by share121** [comment]
谢谢你。但是，大部分人觉得脚本更新的太频繁了，所以我计划在下一个功能性更新中修复

**Comment by match-fire** [comment]
豪德
