### ISSUE TITLE
BUG：刷新按钮出现问题

### ISSUE THREAD

**Issue by capacitor1** [share121/inter-knot#1524]
![image](https://github.com/user-attachments/assets/24179e43-89be-47de-b39d-80ec2ac3e72e)
刷新网页很正常
但是按刷新按钮，就只能显示上面一列帖子了，滚动也不会加载剩下的东西

刷新整个网页：
![image](https://github.com/user-attachments/assets/5e3737e3-d6bc-472b-83db-6d00c719832c)
这是正常的

刷新按钮刷新：
![image](https://github.com/user-attachments/assets/9e3afc7a-3824-4583-a11c-9b1bcfb89d68)
只剩一列了

## 但是！

我把窗口分辨率调小 就又能滚动刷新了

**Comment by share121** [comment]
目前已经修复，谢谢
