### ISSUE TITLE
BUG：评论显示错误

### ISSUE THREAD

**Issue by capacitor1** [share121/inter-knot#1654]
加载大于10F评论的帖子，等1-10F刚刚加载出来，动一下鼠标滚轮触发后面的加载，但是在20F加载出来之前，关闭这个帖子，随便打开一个新的帖子

然后

## 刚刚没加载出来的20F评论就全加载到这个新的帖子里了。。

操作流程：
打开超过10F评论的帖子
![image](https://github.com/user-attachments/assets/0206304b-25d3-439b-8c0f-c30897494577)
等后面的评论没加载出来就切换帖子
![image](https://github.com/user-attachments/assets/8834bfcc-c729-4020-b46d-1c76c4a3a315)

**Comment by share121** [comment]
已修复
