### ISSUE TITLE
[BUG] 预览无视`\n`换行符

### ISSUE THREAD

**Issue by Buer-Nahida** [share121/inter-knot#1708]
# 如标题

## 预览效果：

![图片](https://github.com/user-attachments/assets/c955c8c7-a145-4945-b13c-27a4e871cfb6)

## 实际内容：

![图片](https://github.com/user-attachments/assets/3bcd4c1e-e952-4175-ad36-16ba0fde962b)

**Comment by share121** [comment]
可我限制了只能显示 2 行，如果允许换行符，那么这篇文章的显示效果如下

![screenshot (10)](https://github.com/user-attachments/assets/eea0e0c9-8f8e-47a2-bcdf-c6495842986f)
