### ISSUE TITLE
[Feature] 举报时二次确认

### ISSUE THREAD

**Issue by Buer-Nahida** [share121/inter-knot#1734]
如题，避免某些人“这是什么按钮，点一下试试”

**Comment by InterKnotGuard** [comment]
#1730 如果可以的话顺便把这个也一起添加

**Comment by InfinitumC** [comment]
哦我有个建议，就是可以加一个举报原因，可以在二次确认的时候填写

**Comment by Dave-12138** [comment]
当然，要是没有填写举报理由功能的话，建议用个更便于管理的办法：

- 如果对于举报目标，存在举报相同帖子的comment，则对该comment投票（↑）（说起来有这个api吗）
- 否则创建新的举报comment

否则各位将看到几十个用户发送举报同一个帖子的comment之盛况——事实上已经有了

**Comment by AetherLude** [comment]
> 当然，要是没有填写举报理由功能的话，建议用个更便于管理的办法：
> 
> * 如果对于举报目标，存在举报相同帖子的comment，则对该comment投票（↑）（说起来有这个api吗）
> * 否则创建新的举报comment
> 
> 否则各位将看到几十个用户发送举报同一个帖子的comment之盛况——事实上已经有了

或者说不用投票也可以，我想就是说识别有没有举报同一个帖子的评论，如果有的话直接回复那个评论就好了，而不是新开个评论

**Comment by wuyuncheng-26** [comment]
现在暂时不用了，换成在 DC 举报了，门槛又高了一点
应该不会再出什么小鬼恶意举报了

**Comment by share121** [comment]
有举报原因了

**Comment by Buer-Nahida** [comment]
没实现啊！！！！！！！！！！！！！！！！！！！！！！！！！！！
