### ISSUE TITLE
【BUG】按钮的链接错误

### ISSUE THREAD

**Issue by user1-cloud** [share121/inter-knot#1771]
绳网页面右上角的“GitHub”按钮和右下角的“写文章”按钮的链接中的“store.owner”应该为“share121”。愿尽快修复谢谢
现在点进去是空的页面
![image](https://github.com/user-attachments/assets/1bd64e9b-f694-4ee4-82a0-1103b0740b2a)

**Comment by share121** [comment]
修好了
