### ISSUE TITLE
顶栏选项卡动画改进

### ISSUE THREAD

**Issue by Lukoning** [share121/inter-knot#1999]
浅改了一下顶栏Tab动画，但我没找到前端文件（似乎是动态生成的？），于是放到issue里了

起因是在B站上刷到了视频，进来看发现Tab的动画挺…
正好之前做过绝区零样式的按钮（专门校对过，与游戏内效果高度相似），于是就现场修改了

以下是对比视频（建议在新选项卡打开）
修改前：
https://github.com/user-attachments/assets/01aa512a-dd9a-4fe4-95ac-b0d09c5237f0
修改后：
https://github.com/user-attachments/assets/57d0474b-ada4-4555-8e10-e83537e0bd4d

做了改动的CSS代码
```
.tab-container .tab.active[data-v-77dd3e63]:after, .tab-container .tab.active[data-v-77dd3e63]:before {
    animation:
        tab-color-77dd3e63 .725s linear infinite alternate,
        tab-size-77dd3e63 .319s cubic-bezier(.8, 0, .7, .35) infinite alternate;
}

@keyframes tab-color-77dd3e63 {
    0% {
        background: rgb(255, 222, 0);
    }
    100% {
        background: rgb(145, 188, 0);
    }
```

**Comment by share121** [comment]
谢谢你，他原本是一样快的，我觉得晃眼所以改慢了

**Comment by Lukoning** [comment]
也许可以写一个选项，允许用户在快与慢之间切换……？
