### ISSUE TITLE
对于等级和每日任务机制写了一个大纲，能提一下意见不？

### ISSUE THREAD

**Issue by nostalgiatan** [share121/inter-knot#2059]
发帖子+100（每日上限0/2）
写回复+30（每日上限0/10）
每日阅读帖子近30秒<避免秒退>+30（每日上限0/20）
———————————————————
不太清楚，风纪委员或者还有其他职位的人员任职天数是怎么算的？如果是按天来算的话，任职一天每天额外+100？当然，似乎也可以按绩效来算，举报成功一个+50（每日上限0/20），这个我还不太了解。

这个套路还是比较老的，但这是一个论坛，目前也新不出来，或许有一些小游戏做出来了，可以做成一个活动好像也OK

不过这个工序是挺复杂的，每日任务这个可以添加到日程这个栏目里，还要添加什么就不太了解了，或许可以把功能性版本更新信息放在上面，放在日程的正上面用来显示公告，然后下面写出每日任务，似乎也不是不可以。

按照绝区零的等级规划来看，他获取经验的方式有很多，所以他的等级可以这么列，当然我们也可以这么列，只要我们获取经验的方式足够就可以了。

最后这个绳网等级这个栏目实在是想不到该填什么了，这个栏目在游戏里面就是个领福利的地方，但是搬到论坛里面，它可以用来做什么呢？

下面是绝区零绳网等级所需经验划分，以及我对等级认证后的每日任务奖励提升的考虑，当然没有参考现实可能会有些不太周到的地方，呃，反正现在这个玩意还没做出来，可以看看反馈等优化嘛。

等级—到下一个等级所需经验
LV1—245
LV2—320
LV3—400
LV4—475
LV5—555
LV6—635
LV7—710
LV8—790
LV9—870
LV10—950
LV11—1025
LV12—1105
LV13—1185
LV14—1260
LV15—1340
LV16—1415
LV17—1495
LV18—1575
LV19—1650
LV20—2165
等级认证——正式绳匠
每日任务各上限提升至
（3/15/30）

LV21—2595
LV22—3025
LV23—3455
LV24—3885
LV25—4315
LV26—4745
LV27—5175
LV28—5605
LV29—6035
LV30—6465
等级认证——资深绳匠
每日任务各上限提升至
（5/20/40）

LV31—6895
LV32—7325
LV33—7755
LV34—8185
LV35—8615
LV36—9045
LV37—9475
LV38—9905
LV39—10335
LV40—10820
等级认证——精英绳匠
每日任务奖励各提升40%

LV41—11300
LV42—11780
LV43—12260
LV44—12740
LV45—13225
LV46—13705
LV47—14185
LV48—14665
LV49—15145
LV50—35000
等级成就——传奇绳匠
每日任务奖励各提升100%

LV51—48265
LV52—61525
LV53—74790
后面的目前不知道后续再添，反正光53级就够很一阵子了

**Comment by share121** [comment]
挺好的
