### ISSUE TITLE
[是BUG还是彩蛋？] 有几率触发已经修复的滚动BUG

### ISSUE THREAD

**Issue by minyue-yu** [share121/inter-knot#2065]
[运行环境]
Windows 10 Pro 22H2
Google Chrome 127.0.6533.120（正式版本） （64 位）
香港梯子
[触发方式]
距离顶部三到四个帖子靠近左侧的 由share121发布的 标题为 [原神] 的帖子 从“用户名”处打开帖子 快速下滑（有时不需要）可用触发
触发几率 ：国内网络几率较大 但还是几率<1%
在性能良好的计算机上几率<0.1%
必须是 由share121发布的 标题为 [原神] 的帖子 或 其他管理员的帖子      注：普通帖子不会触发
怀疑是分享功能导致加载不完全
过一段时间切回绳网这个几率大大增加

很迷
玄幻

**Comment by minyue-yu** [comment]
![捕获](https://github.com/user-attachments/assets/2d161109-0433-4216-81fa-9bf7540f7119)

**Comment by minyue-yu** [comment]
如果是置顶几率翻倍

**Comment by share121** [comment]
这应该是 bug，不过我按照你的方法无法复现
