### ISSUE TITLE
【意见】添加ID与名称对照表

### ISSUE THREAD

**Issue by Enigma-Soul** [share121/inter-knot#2099]
众所周知 绳网上的ID可以是中文 但Github只能是英文 还不能重复 所以建议做一个ID对照表 优先显示对照表上的名称 当然 头像也如此

附：
第一发十连
![屏幕截图 2024-08-14 181441](https://github.com/user-attachments/assets/7b70828e-2475-43e9-9eca-fa7a1ea20864)

**Comment by Dave-12138** [comment]
不能重复且限制字符范围的是id，但github是可以起“名字”的，名字可以用中文
从api直接拿就可以了
另：怎么没人封晒卡的

**Comment by Enigma-Soul** [comment]
据我所知，绳网用的是ID，只能用英文

**Comment by Enigma-Soul** [comment]
> 据我所知，绳网用的是ID，只能用英文

况且我们这些人是奔着GIT来的，不怎么改名字
