### ISSUE TITLE
[功能建议]：一个帖子内图片放大的功能

### ISSUE THREAD

**Issue by misaka10384** [share121/inter-knot#2114]
如题，希望可以点击图片放大 或者~~原图显示~~

**Comment by HKLHaoBin** [comment]
这个恐怕做不到，这个图片说到底还是调用的 github 评论上面的图片，如果 github 已经对图片压缩，开发者也无计可施。

**Comment by misaka10384** [comment]
实际上也不需要原图显示啦   只要可以放大图片就行 
因为有时候这个图片是因为缩放问题导致看不清 如果能放大的话就能看清了
![Clip_2024-08-18_01-41-29](https://github.com/user-attachments/assets/69204fb1-3586-4bda-b503-a5ee199c663a)
像比如这个  原图有986x740  但是受限于帖子的问题  图片被压缩到了558x418
