### ISSUE TITLE
［BUG］Edge浏览器在更新绳网助手后显示最新绳网助手为1.8.0，但其他浏览器没有这个问题，这是怎么回事？

### ISSUE THREAD

**Issue by jidianzhuxing** [share121/inter-knot#2115]
如图
![屏幕截图 2024-08-14 195522](https://github.com/user-attachments/assets/bb0746f7-237a-4207-98b4-871453cdccc8)
![屏幕截图 2024-08-14 194820](https://github.com/user-attachments/assets/4b074521-b698-4f5b-be0c-f9acee43d220)

**Comment by Dave-12138** [comment]
之前开了pwa导致github给你留的上古缓存，换[绳网.top](https://www.xn--5o0anh.top/)这个域名就好了

**Comment by share121** [comment]
可以使用 `Ctrl` + `Shift` + `R` 强制刷新网页
