### ISSUE TITLE
[意见]发展方向上的意见

### ISSUE THREAD

**Issue by Pleasurecruise** [share121/inter-knot#2147]
真心想要项目能够发展壮大

作者如果想要做大做强以及维持项目的长久的话，能否参考一下下面的建议

可以考虑新注册个Github账号然后转变成组织，也就是绳网项目组

给想要为仓库编写代码的人读写权限

给审核员读的权限

和每个想要加入项目组的简单沟通一下，检验一下代码的能力，将发展步骤细化到个人（类似于外包），

比如负责UI采集的，负责编写wiki的，负责编写接口的等等，而不是只是现在在功能上的完善和优化

服务器资源或许可以考虑采取众筹的方式......

（连我也觉得好像不太现实......）

 在运作模式上可以参考一下其他的一些大项目，比如说@travellings-link

以Github Discussion来承载论坛的主要评论内容和素材终究不是长远之计

但如果真的要改估计真的是大刀阔斧了，没有一两个月下不来

如果没有这个打算就当我上面没说，打扰了

**Comment by Enigma-Soul** [comment]
要是成组织的话，加我一个
（闲的）

**Comment by Kali-Ivypooler** [comment]
如果规模够大的话，绝区零官方应该会下场支持的

**Comment by Enigma-Soul** [comment]
> 如果规模够大的话，绝区零官方应该会下场支持的

但是github这一门槛就很高了，规模估计大不了

**Comment by capacitor1** [comment]
🤔个人认为，做大做强，中间必定是要投入成本的，因为必定要从GitHub转移到自己的服务器后端上，就服务器这一点都很费钱。这个成本看站长有没有能力。

**Comment by Enigma-Soul** [comment]
> 🤔个人认为，做大做强，中间必定是要投入成本的，因为必定要从GitHub转移到自己的服务器后端上，就服务器这一点都很费钱。这个成本看站长有没有能力。

不一定

**Comment by yyhen1** [comment]
> 

确实，买服务器要氪金，而且后期维护，防止被攻击上面也要下点功夫，现在也不知道目前绳网用户规模达到了什么量级

**Comment by Kali-Ivypooler** [comment]
> 🤔个人认为，做大做强，中间必定是要投入成本的，因为必定要从GitHub转移到自己的服务器后端上，就服务器这一点都很费钱。这个成本看站长有没有能力。

如果前期那样做的话，攻击防护花费的精力与资金可不少，贴吧那边的米黑已经有计划来搞事了，这边的门槛至少可以过滤一部分，我可不希望一个有潜力的项目被一群见不得别人好的黑子整死

**Comment by Enigma-Soul** [comment]
绳网是基于github的交流的 迁移后先不说能不能用 麻不麻烦啊 还要新做交流对话框和后端

**Comment by HKLHaoBin** [comment]
首先评论基于 github 这个大概率改不了，因为有太多规则和安全措施都是依赖 github 的。但是其他的意见提的很好

**Comment by VacuolePaoo** [comment]
现在社区有极小规模的团队，但是作为公益项目，除了B站发的宣传视频没有任何收益
