### ISSUE TITLE
增加视频投稿和主页播放

### ISSUE THREAD

**Issue by whoisfucker** [share121/inter-knot#2355]
支持视频功能，网站主页显示缩略图，并且可以一键播放

在绳网中偷偷建立B站

可以考虑增加等级限制，例如等级3的上传者或用户才能视频一键播放，限制视频长度，减少审核困难

**Comment by HKLHaoBin** [comment]
除非 github 允许放视频到评论上面，否则不可能实现。

**Comment by whoisfucker** [comment]
https://github.com/user-attachments/assets/85b50c51-a113-4cbd-9c35-9e76af9b8080

**Comment by HKLHaoBin** [comment]
把它发送到绳网上去看一下，按道理来说，如果github评论允许视频播放的话，那么绳网也应该是允许视频播放的，从代码的角度来说，它就是一个视频超链接，实现方法并不那么复杂

**Comment by whoisfucker** [comment]
支持是支持，不支持缩略图和一键播放

**Comment by HKLHaoBin** [comment]
我刚试了一下，只支持10兆的视频上传，跟没有一样

**Comment by whoisfucker** [comment]
那真是太可惜了，或者需要油猴支持分块上传，或者等github有一天扩容

**Comment by whoisfucker** [comment]
引用B站视频或油管视频不知道可以吗，例如输入BV号，转义为iframe等方案
