### ISSUE TITLE
帖子可以增加个按发布时间和热度（评论数量）排序

### ISSUE THREAD

**Issue by yyhen1** [share121/inter-knot#2399]

**Comment by HKLHaoBin** [comment]
这个提议不好，是两个极端 容易造成信息茧房

**Comment by HKLHaoBin** [comment]
而且，如果评论信息是直接录入数据库的话，那还有可能实现，但这个他是用了 github 的，如果 github 没有做这个功能，可能就没办法实现排序了，就只能完全按照 github 的顺序。在如此大量的评论数量下做排序是不现实的。除非在数据库建索引，就像你用Python给100000个数字做排序，这个过程是相当慢的。

**Comment by yyhen1** [comment]
以下是个人拙见,后期如果有自己后端的就容易很实现，后期帖子数量增加，若性能不行，就加中间件eg:Redis啥的，缓存一下,排序的话 给帖子表加一个评论数字段，专门统计评论数吧 ,然后说到按发布时间和热度（评论数量）排序 这功能是让用户选择的吧 可开可不开,类似于让B站的评论区可以按热度和时间排序，造成信息茧房的是类似于dy的推荐算法，这种才容易造成信息茧房，一直推荐你喜欢的东西，感觉要想发展起来 还是得有自己的后端，然后只能用github账号登录注册可以不变，就接入github第三方登录吧.有自己后端，后面一系列功能才能扩展，例如可以给帖子贴标签，正如游戏中的一样，有委托，有灌水，什么的，然后还可以接入好友系统什么的，不过服务器的成本也是个大问题
