### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by 6078HITHEDAY** [share121/inter-knot#2401]
# 打不开了 **https://share121.github.io/inter-knot/**
![Screenshot_20240816-161116](https://github.com/user-attachments/assets/4d5aeaa6-f98f-43d3-925d-ef54ddb3ba82)

**Comment by 6078HITHEDAY** [comment]
小助手1.14.0

**Comment by fjhsjdhfhdjjw** [comment]
一样，换了好多次加速器还是一样

**Comment by 6078HITHEDAY** [comment]
> 一样，换了好多次加速器还是一样

try this **https://www.绳网.top/**
镜像站？

**Comment by fjhsjdhfhdjjw** [comment]
写错字了，是浏览器

**Comment by 6078HITHEDAY** [comment]
> 写错字了，是浏览器

评论可以修改的

**Comment by fjhsjdhfhdjjw** [comment]
第一次用，不知道

**Comment by HKLHaoBin** [comment]
> > 一样，换了好多次加速器还是一样
> 
> 试试这个 **[https://www.绳网.top/](https://www.%E7%BB%B3%E7%BD%91.top/)** 镜像站？

不是

**Comment by 6078HITHEDAY** [comment]
# 解决方案
【🔥PWA 毁了我的绳网🔥-哔哩哔哩】 https://b23.tv/Ak4AnIw
