### ISSUE TITLE
希望再开发一下回复功能：

### ISSUE THREAD

**Issue by HKLHaoBin** [share121/inter-knot#2620]
我的设想是：
![image](https://github.com/user-attachments/assets/92dea994-c99d-4380-bfae-042ca3af1bd6)

1. 点击用户头像后跳转
2. 跳转后自动定位到该用户

![image](https://github.com/user-attachments/assets/ddb69488-b44c-4994-a87c-94943b374e7e)

**Comment by share121** [comment]
解决了，点击评论区头像即可
