### ISSUE TITLE
「建议」对于文章举报后的处理方法 我有更好的想法

### ISSUE THREAD

**Issue by HKLHaoBin** [share121/inter-knot#2624]
我的建议是加一个众评，在众评数量超过某个值之后采取行动，这样既解决了不需要AI，而且处理的速度会很快。
比如在评论区加个选项：你认为这个内容（合适）or（不合适 ）

**Comment by VacuolePaoo** [comment]
有没有具体的实施方案，而且现在这个1不就是众评吗，认为不合适的人5个后就隐藏帖子

**Comment by VacuolePaoo** [comment]
已经有了，5个
