### ISSUE TITLE
关于多平台的建议

### ISSUE THREAD

**Issue by Enigma-Soul** [share121/inter-knot#2648]
**以下的建议都不用大规模改写**
- 建议PC使用 Electron.js 毕竟Electron的功能就是把网页转换成App吗
- 建议手机端（安卓）使用 React native 功能和Electron差不多
- 苹果做的话最好别用ipa（自签和移植麻烦的要死），最佳解决办法是微信小程序
---
~~能不能给我来个Contributor~~

**Comment by Enigma-Soul** [comment]
闲的也是闲的
我们这个假期没作业

**Comment by capacitor1** [comment]
作者在dc目前已经表明，用flutter重写客户端了，但因为开学，所以遥遥无期

另：🤔iOS端本身太封闭了，但是微信小程序也不是最好解决方案，要考虑没有微信或者正在抵制微信的人

**Comment by Pleasurecruise** [comment]
习惯用uniapp，给我我能写，而且有空......
