### ISSUE TITLE
BUG？

### ISSUE THREAD

**Issue by bzxs** [share121/inter-knot#2726]
![image](https://github.com/user-attachments/assets/0d805760-be78-4524-9ec1-3b534b88a307)
![image](https://github.com/user-attachments/assets/2769240c-f937-40f4-b8b5-ebe47e4dd8bb)

**Comment by bzxs** [comment]
换成https://www.xn--5o0anh.top/就可以了

**Comment by LeiMoo** [comment]
8月18日20：00，重庆电信宽带和电信手机流量

访问绳网.top，或者https://www.xn--5o0anh.top，跳转到github后有一瞬间同意的界面，但是5s左右就变404了。

**Comment by LeiMoo** [comment]
8月18日20：00，重庆电信宽带和电信手机流量

访问绳网.top，或者https://www.xn--5o0anh.top，跳转到github后有一瞬间同意的界面，但是5s左右就变404了。
