### ISSUE TITLE
貌似是某个家政所的执事吧 之前还看过某个小妹妹跟他索要尾巴毛 他还真的给了

### ISSUE THREAD

**Issue by I-m-Miss-Lucy-s-dog** [share121/inter-knot#2863]
貌似是某個家政所的執事吧 之前還看過某個小妹妹跟他所要尾巴毛 他還真的給了

_Originally posted by @I-m-Miss-Lucy-s-dog in https://github.com/share121/inter-knot/discussions/2859#discussioncomment-10373687_

**Comment by fufumo** [comment]
这是反馈bug的地方啊
