### ISSUE TITLE
[Bug]安卓端会反复加载

### ISSUE THREAD

**Issue by haha252** [share121/inter-knot#300]
在安装插件+github授权后
会反复加载，具体症状为“https://share121.github.io/inter-knot/?code=xxxxxxxx”后面这一串xxxxxx会一直变

**Comment by c1iied** [comment]
我这也是这个问题，已经放弃从手机端进去了

**Comment by CJYKK** [comment]
Android System Webview 126.0.6478.188
Via 5.8.1
未能复现此问题。

**Comment by share121** [comment]
可能是你的“绳网跨域助手”版本太旧
