### ISSUE TITLE
有没有本地部署的童鞋啊

### ISSUE THREAD

**Issue by aynuzbh** [share121/inter-knot#3416]
我本地部署了，但似乎只把read.me拉过来了，笑不活了真的是
https://zzz.aynu.asia

**Comment by yuxwd** [comment]
这个node.js的项目的话，应该可以本地部署吧

**Comment by yuxwd** [comment]
这个node.js的项目的话，应该可以本地部署吧,我试一下，看看可不可以

**Comment by rong-xiaoli** [comment]
本地部署可行但没有什么意义，你直接clone gh-pages分支到本地即可
