### ISSUE TITLE
感觉我心都要死了

### ISSUE THREAD

**Issue by wenkui921** [share121/inter-knot#3467]
感觉我心都要死了
![17242696935028e14fd1cb8efe2353fee14e90dc3c6a351a225726696d54aefe35cebe41c70cc 0_edit_508824201317671](https://github.com/user-attachments/assets/bc0ffc29-576c-4096-b3b4-4996178415fa)
什么时候我才能用上能看陌生人帖子的绳网呢
![17242696935028e14fd1cb8efe2353fee14e90dc3c6a351a225726696d54aefe35cebe41c70cc 0_edit_508824201317671](https://github.com/user-attachments/assets/802767b4-11bd-4a97-9346-0c698031d997)

_Originally posted by @wenkui921 in https://github.com/share121/inter-knot/discussions/3466_

**Comment by rong-xiaoli** [comment]
不要发到issues里啊喂
