### ISSUE TITLE
求回复一下网络问题，本人网络小白

### ISSUE THREAD

**Issue by jiumoqingfeng** [share121/inter-knot#3506]
我这边今天下午看到了绳网，然后头一次搭梯子上去了绳网发了帖子。然后今天晚上再上绳网的时候就是无法访问网站。之前翻了一下看到说开启的时候油猴里开个什么东西，我这边他也没弹界面，我油猴也没翻到（因此不确定是不是因为这个没开:)。总之就是绳网上不去了。
电脑和手机端都试了，不知道哪里出的问题，有没有大手子能回复一下看看。

**Comment by jiumoqingfeng** [comment]
我是因为收到回复了才想着再上绳网看看的，结果就完蛋上不去了。基础术语能看懂，如果解决这个问题需要我了解网络知识的话直接说术语就行，谢谢。

**Comment by jiumoqingfeng** [comment]
> 你登的是绳网.top吧？这个链接现在不稳定，大概率是登不上去的，你换一个链接登一下，这个是老链接，应该是可以登进去的，如果没登进去，那大概就是其他问题了。https://share121.github.io/inter-knot/

多谢，已解决。

**Comment by zhizhizhiwang** [comment]
已解决麻烦关掉issues谢谢（
