### ISSUE TITLE
[Suggestion] 请抽空检查域名的备案问题

### ISSUE THREAD

**Issue by liubanlaobanzhang** [share121/inter-knot#3534]
首先恭喜 UP 出狱（不是）
![image](https://github.com/user-attachments/assets/3ecc5685-805b-45be-8f49-115fc3bb60f5)
这是你的域名解析情况……
尽管 Whois 可以查到，但是由于`没有备案`，你的网站看起来和之前的`爱发电/123云盘`一样停掉了解析……
> 按照政策要求，服务器在大陆地区的域名接入均需办理备案，备案成功并获取通信管理局下发的 ICP 备案号后才能开通访问。

但是我知道 UP 刚上高中学业很忙，再加上这个网站类型以及管理问题，感觉去申请 ICP 备案可能性不大……
所以是不是考虑……换个域名服务商什么的？

**Comment by aynuzbh** [comment]
阿里云一块钱买域名，CF加速github就行了
