### ISSUE TITLE
[建议]增加新人引导部分

### ISSUE THREAD

**Issue by zhizhizhiwang** [share121/inter-knot#3541]
能看到有(很多)人为了上绳网而注册GitHub账号。对于这部分缺少GitHub等平台使用经历的人群，是否需要相应的内容进行引导，例如介绍Github平台，Issues和Discussions板块作用，~~提问的智慧~~ 等。（推动电子扫盲，减少赛博巨婴（bushi

**Comment by rong-xiaoli** [comment]
对于Issues部分，我已经提交了一个PR： #3309 
对于板块作用建议挪到置顶帖中
对于GitHub平台介绍，建议作者出一期视频

**Comment by VacuolePaoo** [comment]
本来就是需要设置一点门槛，避免乌烟瘴气
