### ISSUE TITLE
Safari17.6安装扩展后无法正常刷新页面

### ISSUE THREAD

**Issue by QuasarRyan** [share121/inter-knot#3719]
### Type

其他问题

### Bug 描述

我在使用macOS14.6.1上的Safari17.6浏览器打开绳网并安装“绳网跨域助手”的扩展之后，页面无法正常刷新，没有正常跳转至登录界面，始终提示我“请安装‘绳网小助手’”。在卡法选项中选择清空页面缓存后依旧无法解决。我已科学上网。Chrome上则一切正常。

### 截屏或视频

<img width="1512" alt="inter-knot-issue" src="https://github.com/user-attachments/assets/d9fa3399-265f-4617-b9af-ab0024d1b8a0">
<img width="1512" alt="inter-knot-issue2" src="https://github.com/user-attachments/assets/8cd0d3f0-eda8-4cda-af3d-f13a5e9f567f">

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by QuasarRyan** [comment]
右上角的图标也刷新不出来

**Comment by share121** [comment]
请卸载脚本，并访问新域名 inot.top
