### ISSUE TITLE
[建议]Disscusion部分Category类型调整

### ISSUE THREAD

**Issue by Pleasurecruise** [share121/inter-knot#3746]
### Type

功能建议

### Bug 描述

要适应https://share121.github.io/inter_knot/的”分区“部分
Disscusion这里的标签是不是也可以按——GI，SR，ZZZ来分类

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by share121** [comment]
好的已实现，请访问新域名 inot.top
