### ISSUE TITLE
绳网的帖子评论在手机版是竖着的

### ISSUE THREAD

**Issue by daoyeeqq121** [share121/inter-knot#3773]
### Type

其他问题

### Bug 描述

打开就是这样，感觉是排版的问题，还是说可以改？

### 截屏或视频

![Screenshot_2024-08-28-10-37-58-556_com example inter_knot](https://github.com/user-attachments/assets/6750d3fb-c87a-4177-98ef-9fde01ea848c)

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [x] 我确认。

**Comment by share121** [comment]
已解决，请访问新域名 inot.top
