### ISSUE TITLE
未来支持个人部署吗？

### ISSUE THREAD

**Issue by MKStoler4096** [share121/inter-knot#3774]
如题。主要是觉得可以成为一个静态贴吧，省钱😍

**Comment by NiuBoss123** [comment]
跨域问题是重头，我试着 fork 然后 vercel 部署直接冒出一堆问题（主要问题在油猴插件，复制然后瞎改了一下不知道改对了没）
不过若是抛掉跨域问题，本身这一套 UI 就是一个很好的模板，只是缺少个合适的后端

**Comment by share121** [comment]
已经开发出了 app 版，修改 lib/data.dart 中的数据即可完成部署
