### ISSUE TITLE
[bug]无法正常打开绳网,api速率限制已到达

### ISSUE THREAD

**Issue by Stoneyinyu** [share121/inter-knot#3841]
![屏幕截图 2024-08-30 153608](https://github.com/user-attachments/assets/60626a77-05fa-4509-be29-2f134aa8adae)
![屏幕截图 2024-08-30 153720](https://github.com/user-attachments/assets/b6f7f419-c9a3-494d-9f30-5e65b151cc41)

**Comment by WhiteXBXB** [comment]
我也是这样

**Comment by share121** [comment]
因为查看帖子不用登录，导致 api 被别人刷爆了

**Comment by Maixiaofanqie** [comment]
+1，所以怎么搞啊

**Comment by share121** [comment]
已解决，请访问新域名 inot.top

**Comment by RGthx** [comment]
### 
似乎app端仍有此bug
![Screenshot_2024-09-01-00-52-04-553_com example inter_knot](https://github.com/user-attachments/assets/316a0da2-77db-48af-9435-e66fca1befc4)
