### ISSUE TITLE
绳网打不开显示这个，咋整？

### ISSUE THREAD

**Issue by dong200497** [share121/inter-knot#3842]
![屏幕截图 2024-08-30 155357](https://github.com/user-attachments/assets/2cfc5103-7a35-47f9-a5c7-9085ae404126)

**Comment by WhiteXBXB** [comment]
我也是这样

**Comment by qyn423520** [comment]
我也是

**Comment by rong-xiaoli** [comment]
别急，换了架构正在调整： #3843

**Comment by share121** [comment]
请访问新域名 inot.top
