### ISSUE TITLE
[BUG] Weird blur effect on the side of web client 网页端莫名的模糊效果

### ISSUE THREAD

**Issue by rong-xiaoli** [share121/inter-knot#3847]
![image](https://github.com/user-attachments/assets/cf064e32-2327-4bce-834d-84aec70e3b8e)
左边是靠中间的，右边是靠网页边的，不知道为什么有个模糊效果？应该不是我的错觉吧

**Comment by share121** [comment]
这是 flutter 的问题，没法解决，建议使用 app 端
