### ISSUE TITLE
[建议 安卓端] 移动应用侧边栏与返回手势冲突，希望增加隐藏状态栏以达到侧边栏完全显示

### ISSUE THREAD

**Issue by minyue-yu** [share121/inter-knot#3860]
### Type

功能建议

### Bug 描述

如标题所示

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by qjksxy** [comment]
屏幕左侧下方三分之二的区域，滑动为返回，上方三分之一的区域，滑动为侧边栏，两个手势并不冲突。
隐藏状态栏是什么意思？
