### ISSUE TITLE
MacOS 关闭窗口按钮问题

### ISSUE THREAD

**Issue by AetherLude** [share121/inter-knot#3875]
### Type

其他问题

### Bug 描述

1. MacOS绳网有两套 最小化/全屏/关闭窗口 的按钮，一套是苹果自带的，一套是绳网APP的，可以考虑移除一套（苹果的和UI有点冲突）
2. 绳网原生的窗口按钮其中 最小化窗口 和 全屏窗口 这两个按钮失效了，无法使用，只有关闭窗口按钮能正常使用

绳网APP版本：V2.8.0+9版本以及改版本前的所有绳网MacOS版本应该都有这个问题
请看下面图片的右上角和左上角

### 截屏或视频

![截屏2024-09-01 上午12 13 27](https://github.com/user-attachments/assets/914f4abb-7380-4721-8b54-3f80fe446254)

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by share121** [comment]
已解决
