### ISSUE TITLE
希望可以出一个ios版本，巨魔用户可以直接安装

### ISSUE THREAD

**Issue by CarlBobi** [share121/inter-knot#3940]
唯独少了ios端，希望可以出一个ios版本，巨魔用户可以直接安装ipa包

**Comment by KleeForever** [comment]
可以试一下ALT store自签名软件来实现

**Comment by CarlBobi** [comment]
> 可以试一下ALT store自签名软件来实现



> 可以试一下ALT store自签名软件来实现

需要IPA包，目前没有ipa包

**Comment by Yizakl** [comment]
https://github.com/share121/inter-knot/discussions/4893#new_comment_form  来看看我的帖子罢qwq
（写得可能不好

**Comment by share121** [comment]
已实现
