### ISSUE TITLE
关于电脑端的问题

### ISSUE THREAD

**Issue by ERoTiN** [share121/inter-knot#3953]
1. api请求过多的弹窗真的很烦，我就以刷网页版的B站的速度点了几下就叠加弹出来好多个。
2. 每次退出帖子都会刷新一下，不仅掉帧而且好像会导致出现第一个问题。
3. 帖子分区真得有，现在全是乱七八糟的帖子占满屏幕

**Comment by ERoTiN** [comment]
用户api试过了，登不上。我意思没说明白，的第三个的意思是推荐里的应该把灌水之类的分类给屏蔽吧，现在的推荐叫全部不叫推荐。

**Comment by ERoTiN** [comment]
> API请求过多可以换用户API吧，还有就是不是有分区吗？你在分区里面找自己想要的分区也行，你搜索关键词，寻找你想要看的内容也行吧。

网页版用户api试过了，登不上，不过下载下来就能登陆了。我意思没说明白，的第三个的意思是推荐里的应该把灌水之类的分类给屏蔽吧，现在的推荐叫全部不叫推荐。

**Comment by share121** [comment]
> api请求过多的弹窗真的很烦，我就以刷网页版的B站的速度点了几下就叠加弹出来好多个。

现在加入限制，每 5 秒才能刷新一次

> 每次退出帖子都会刷新一下，不仅掉帧而且好像会导致出现第一个问题。

已解决

> 帖子分区真得有，现在全是乱七八糟的帖子占满屏幕

未来会有
