### ISSUE TITLE
【建议】【低优先度】Android 端图标适配显示问题

### ISSUE THREAD

**Issue by eppzrypt** [share121/inter-knot#4087]
### Type

功能建议

### Bug 描述

Android 端桌面图标有白边且圆角矩形显示被裁切

![41725219310_ pic](https://github.com/user-attachments/assets/20db62a2-80e6-4362-bbc6-d55efbdb51dd)

适配可参考文章[Android应用图标微技巧，8.0系统中应用图标的适配](https://cloud.tencent.com/developer/article/1456330)

<img width="407" alt="ksuh3belyd" src="https://github.com/user-attachments/assets/d8d1ff75-516e-499a-aea5-9a65c195dd23">

_**另 查看资源文件发现当前图标外圈有一圈白边 并不太好进行适配 建议移除外圈白边 底色黑色中间白色绳网图标更简单**_

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by share121** [comment]
解决
