### ISSUE TITLE
关于优化用户体验

### ISSUE THREAD

**Issue by clouddream520** [share121/inter-knot#4105]
在发帖和评论时需要去其他浏览器页面

是否可以在绳网中内置一个浏览器内核或github，但限制只能在github以及绳网关联网址使用。减少跳转至其他浏览器的时间。

同上一条，在用用户接口时也要跳转至浏览器页面，如果直接调用绳网中内置软件，应该可以用脚本一键完成调用用户接口。 

完成这些应该可以提高流畅度，如果不能，当我在放屁

**Comment by link-fgfgui** [comment]
其实如果去搜你就会知道github是有非常完善的api的,不需要内置浏览器

**Comment by share121** [comment]
手机端已实现在内置浏览器中打开
