### ISSUE TITLE
用戶接口登入異常

### ISSUE THREAD

**Issue by lambda1280** [share121/inter-knot#4133]
### Type

网络问题

### Bug 描述

Error: Failed to get access token

DioException [bad response]: This exception was thrown because the response has a status code of 500 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 500 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by natsumerinchan** [comment]
Chrome上则是
```
DioException [connection error]: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library.
```

控制台上显示
```
Access to XMLHttpRequest at 'https://github.com/login/device/code?client_id=xxxxx' from origin 'https://www.inot.top' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.dart.js:64379 
        
        
       POST https://github.com/login/device/code?client_id=xxxxx net::ERR_FAILED 200 (OK)
```

**Comment by 9563067** [comment]
手机上是你这个报错，
网页端则是：
> DioException [connection error]: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library.

**Comment by Cherry-you** [comment]
问题相同，chrome浏览器登录不上去

**Comment by share121** [comment]
登录接口涉及跨域，可用 Allow CORS 扩展。
500 错误为 github 服务器错误，我无法解决，不过我的程序会自动重试
