### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by xiaochun404** [share121/inter-knot#4313]
### Type

其他问题

### Bug 描述

Error: Failed to get access token

DioException [connection error]: The connection errored: Failed host lookup: 'github.com' This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Failed host lookup: 'github.com' (OS Error: No address associated with hostname, errno = 7)

### 截屏或视频

Error: Failed to get access token

DioException [connection error]: The connection errored: Failed host lookup: 'github.com' This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Failed host lookup: 'github.com' (OS Error: No address associated with hostname, errno = 7)

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by hk0852** [comment]
我是在手机登录上遇到这这个问题的，电脑上好像没有是不是因为要挂梯子的问题，因为我手机上用梯子用起来比较麻烦(>﹏<)

**Comment by share121** [comment]
这个报错是无所谓的，因为我的程序会自动重试。只要能够登录就行了
