### ISSUE TITLE
能不能麻烦把登录改进一下，谢谢

### ISSUE THREAD

**Issue by LingHe9639** [share121/inter-knot#4359]
现在是每次我手误把绳网从后台清出去，就得再重新登录一遍，但是这种情况下总是加载不出登录页面，就导致我得卸载绳网重新下一遍，很麻烦。能麻烦创始人大佬或者其他大佬把登录功能改进一下吗，谢谢。

**Comment by LingHe9639** [comment]
> 你是觉得清后台后重新登录麻烦？还是无法二次登陆麻烦？我这边可以二次登陆，是不是网络问题？

有可能是因为网络问题，我这网有点不稳定。但是每次都要重新登录确实很麻烦。

**Comment by share121** [comment]
并没有吧，一次登录可以 6 个月不重复登录。
我去上学前登录了，5 天后回家，还是可以直接用，并没有反复要求登录

**Comment by Kali-Ivypooler** [comment]
> 并没有吧，一次登录可以 6 个月不重复登录。 我去上学前登录了，5 天后回家，还是可以直接用，并没有反复要求登录

app端开梯子的情况下有时候需要输两次码验证，有时候就不用，其他的正常
