### ISSUE TITLE
各位，iOS用via浏览器装了js脚本、登了GitHub还是一点反应没有啊

### ISSUE THREAD

**Issue by kasumikouta** [share121/inter-knot#438]
![image](https://github.com/user-attachments/assets/2da2e356-65d4-4104-8ef8-74bdfc70d5af)

**Comment by InterKnotGuard** [comment]
可能是网络问题？

**Comment by minyue-yu** [comment]
脚本加载器的问题 100%

**Comment by minyue-yu** [comment]
选择可用安装扩展插件的浏览器安装篡改猴

**Comment by minyue-yu** [comment]
有一部分是WebView过于老旧，导致脚本加载器无法正常工作

**Comment by minyue-yu** [comment]
另一部分可能是浏览器内核的原因，一般出现在老旧内核

**Comment by minyue-yu** [comment]
另一部分可能是浏览器内核的原因，一般出现在老旧内核，或非标准内核 ，或魔改定制内核
或者系统原因，或浏览器原因
实例
我的朋友在我的指导下更换了浏览器+脚本加载器才能使用 原因:（old system）（old WebView）

**Comment by Nahida10271027** [comment]
好家伙我也是，不过我的vivo手机又能登上

**Comment by InterKnotGuard** [comment]
emm看了看，应该是via浏览器的问题，换个浏览器吧

**Comment by Kali-Ivypooler** [comment]
用加速器或梯子试试

**Comment by share121** [comment]
请卸载脚本，并访问新域名 inot.top
