### ISSUE TITLE
[feature]删除帖子

### ISSUE THREAD

**Issue by Buer-Nahida** [share121/inter-knot#448]
Github Discussions不提供删除功能，和Issues、Pull requests一样，或许可以检测状态，把状态为Closed的帖子移出首页？

**Comment by xxtg666** [comment]
（其实是有的，但只有仓库owner能删

**Comment by InfinitumC** [comment]
或者不在绳网首页显示closed的帖子

**Comment by VacuolePaoo** [comment]
很好的功能，share121又要肝代码了

**Comment by share121** [comment]
实现了
