### ISSUE TITLE
[建议] 希望能保留回APP发布前的绳网主界面和帖子内容栏

### ISSUE THREAD

**Issue by Junjun280** [share121/inter-knot#4800]
### Type

功能建议

### Bug 描述

我一向都觉得之前绳网主界面做的挺还原的，自从更新了APP，随着浏览器上面的绳网也更新后，也没有了一开始的还原的主界面和帖子内容栏，希望能添加回绳网之前的主界面和帖子内容栏，菜单可以不用改。

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by Junjun280** [comment]
是啊，说是说很简单，确实做就很难咯，期待一下

**Comment by share121** [comment]
大部分还原了
