### ISSUE TITLE
WindowsAPPv2.16.0+27版本加载帖子好慢，比网页版还慢甚至不加载了

### ISSUE THREAD

**Issue by Junjun280** [share121/inter-knot#4817]
### Type

其他问题

### Bug 描述

WindowsAPPv2.16.0+27版本加载帖子好慢，比网页版还慢甚至不加载了

### 截屏或视频

![屏幕截图 2024-09-12 225826](https://github.com/user-attachments/assets/e5b4c8a1-0610-47f0-b9d7-910d06521581)

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by share121** [comment]
已解决
