### ISSUE TITLE
优化UI建议

### ISSUE THREAD

**Issue by 596wjr** [share121/inter-knot#4819]
### Type

功能建议

### Bug 描述

可以通过github的api等功能实现在页面左上角还原游戏内的头像和用户名

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by Junjun280** [comment]
它之前还没出APP版本，之前是有还原过的，不过现在用了APP就没有了那版，希望能改回来<img src="https://img-static.mihoyo.com/communityweb/upload/9249bd36125b953ddd445b19151427d6.png" alt="安比 疑惑" width="75" >

**Comment by share121** [comment]
实现了
