### ISSUE TITLE
[反馈]关于邮箱消息

### ISSUE THREAD

**Issue by mengsiliulian** [share121/inter-knot#4897]
### Type

安全问题

### Bug 描述

为什么一个从来没有看过或者只看过一眼的帖子也会给我发消息呀！邮箱快炸了！

### 截屏或视频

![Uploading Screenshot_20240915_154714_com.tencent.androidqqmail_edit_269248362004227.jpg…]()

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by share121** [comment]
点击这个按钮

![image](https://github.com/user-attachments/assets/b92b5ead-fa57-430b-a032-23f6225a2e0e)

使它变为

![image](https://github.com/user-attachments/assets/a25dadaa-9352-4dfd-9820-fc427705ef6c)

这样你就不会收到消息了
