### ISSUE TITLE
[提问] 作者以后会打算整个服务器，拓展视频内容存放吗？ 

### ISSUE THREAD

**Issue by Junjun280** [share121/inter-knot#4999]
### Type

功能建议

### Bug 描述

作者以后会打算整个服务器，拓展视频内容存放吗？ 因为我发现github只能上传10M的文件。是否有长远计划整个服务器，或者搞个众筹服务器什么的

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by share121** [comment]
抱歉，这不行
