### ISSUE TITLE
是这种吗？ https://www.shdf.gov.cn/ （扫黄打非网站

### ISSUE THREAD

**Issue by Quan2024-zzz** [share121/inter-knot#5057]
是这种吗？ https://www.shdf.gov.cn/ （扫黄打非网站）

**Comment by Junjun280** [comment]
您是不是发错地方了？

**Comment by Junjun280** [comment]
应该发评论页面而不是这里反馈页面

**Comment by Junjun280** [comment]
![Screenshot_2024-09-17-18-23-39-759_com android chrome-edit](https://github.com/user-attachments/assets/1f650d22-db4a-40bf-bfa3-20f565abf283)
点击关闭问题，就是那个紫色勾就行了
