### ISSUE TITLE
切换为用户接口后报错

### ISSUE THREAD

**Issue by xiaqizhengzhao** [share121/inter-knot#5065]
### Type

网络问题

### Bug 描述

DioException [connection error]: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library.

### 截屏或视频

![Snipaste_2024-09-17_15-43-56](https://github.com/user-attachments/assets/20ca327e-5497-4d48-9543-d265d1a29ede)

### 您确认您已经阅读了上方的注意事项，并已知此处并非讨论区。您遇到了问题需要反馈，或有功能建议需要提出。

- [X] 我确认。

**Comment by xiaqizhengzhao** [comment]
并且没有切换选项容易卡在这个界面

**Comment by Lephaethon** [comment]
你是哪个浏览器，就点击下载哪个扩展。然后看使用说明
![image](https://github.com/user-attachments/assets/1c6fe7db-bc84-402f-9c12-d874d65d2412)
看，方框里面就是使用说明

**Comment by xiaqizhengzhao** [comment]
谢谢
