### ISSUE TITLE
建议：自动刷新帖子内容

### ISSUE THREAD

**Issue by capacitor1** [share121/inter-knot#672]
**支持实时在线刷新帖子**
![image](https://github.com/user-attachments/assets/8614da0b-3cc9-4bdf-9cf3-ed6739ded9ea)

目前要看新内容就只能手动刷新，刷新一次会用很长时间，图片反复加载，影响观感
可以整一个类似于heartbeat的东西，客户端每隔一段时间就请求一次GitHub，如果有新的内容，就更新一下但是不是全部刷新
🤔
这样可以避免因为网络环境和文件过多导致的加载慢负载大的问题

**Comment by Mayf1ower** [comment]
支持！希望写完回复后能够自动刷新一下，不然刷新之后要找自己评论的帖子还蛮麻烦的
同时希望评论区里自己的名字能用不同的颜色显示，方便找到自己的评论😀

**Comment by share121** [comment]
> 自己的名字能用不同的颜色显示

现在实现了

> 自动刷新

目前实现了半自动刷新
