### ISSUE TITLE
【建议】是否考虑使用游戏中的字体

### ISSUE THREAD

**Issue by zdxiaoda** [share121/inter-knot#769]
路径 ZenlessZoneZero_Data\StreamingAssets\MiHoYoSDKRes\HttpServerResources\font\zh-cn.ttf
字体压缩参照 https://github.com/KonghaYao/cn-font-split

**Comment by share121** [comment]
这个字体不是免费商用的

**Comment by 2694281510** [comment]
只要不收费就不算商用吧
