### ISSUE TITLE
标签分配与帖子内容归纳

### ISSUE THREAD

**Issue by nostalgiatan** [share121/inter-knot#780]
按目前的UI设计来看，既然右边已经有了写贴子的图标，建议在左边添加一个菜单类似于绝区零的分类菜单。
**首页**（随机出现帖子）
**咖啡馆**（注水帖子）
**金手指**（游戏分享）
**三Zstudio**（官方资讯）
**治安局**（反馈与建议）

**Comment by HKLHaoBin** [comment]
这个可以有 而且看起来好像比较好实现的样子。

![Clip_2024-08-18_01-53-59](https://github.com/user-attachments/assets/1d39eed6-84f9-4368-a54f-b8fd2edc4b99)
