### ISSUE TITLE
【建议】不要使用新标签页打开帖子发布页面和回复页面

### ISSUE THREAD

**Issue by SDCOM-0415** [share121/inter-knot#788]
如题

**Comment by minyue-yu** [comment]
这个功能是基于github的discussions功能的，要改也要等待up更换第三方评论系统

**Comment by minyue-yu** [comment]
这个功能是基于github的discussions功能的，要改也要等待up更换第三方评论系统

**Comment by minyue-yu** [comment]
这个功能是基于github的discussions功能的，不好改

**Comment by SDCOM-0415** [comment]
> 这个功能是基于github的discussions功能的，不好改

这个部分似乎不属于GitHub的
跳转又有本标签页跳转和新标签页跳转的方式
