### ISSUE TITLE
[建议]各种使用反馈

### ISSUE THREAD

**Issue by TrafficLight6** [share121/inter-knot#865]
![blue](https://github.com/user-attachments/assets/85215437-b20a-4ad0-9bb7-783fe5afab6c)
- 无法支持彩色文字。比如这个帖子，它之前是的标题是彩色的，现在换框架后就无法支持彩色文字。
 ![image](https://github.com/user-attachments/assets/33e1f674-1107-409e-bb79-dbb8b486a255)
- 划到底端后不会自动加载出新的帖子。换句话说，就是只会展示最近的帖子。
- 希望可以解决跨域的问题。
- 看作者应该是使用了第三方的流量统计工具，但是帖子上的浏览量全是977。而更换框架前是正常显示帖子浏览数量的（不清楚其是否为随机数）。
- 希望可以加入上划刷新，用户可以不用手动刷新浏览器

**Comment by VacuolePaoo** [comment]
没有使用busuanzi这样的统计，是随机生成的

**Comment by VacuolePaoo** [comment]
删除了html语法是防止滥用，不是换框架的缘故
