### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by user7314** [share121/inter-knot#876]
为什么我按照up主的方法无法打开绳网？加速器（steam++）已经挂好了，github能上但是绳网不行

**Comment by Mayf1ower** [comment]
是不是没有安装绳网跨域助手（一个跨域访问脚本）？

**Comment by user7314** [comment]
> 是不是没有安装绳网跨域助手（一个跨域访问脚本）？

按教程应该我打开时它应该提示我的，但是浏览器直接说打不开网页

**Comment by Mayf1ower** [comment]
> > 是不是没有安装绳网跨域助手（一个跨域访问脚本）？
> 
> 按教程应该我打开时它应该提示我的，但是浏览器直接说打不开网页

截个图我看看呗

**Comment by user7314** [comment]
> > > 是不是没有安装绳网跨域助手（一个跨域访问脚本）？
> > 
> > 
> > 按教程应该我打开时它应该提示我的，但是浏览器直接说打不开网页
> 
> 截个图我看看

![？](https://github.com/user-attachments/assets/3748acbb-7874-4258-bcbe-0de0802fbd5a)
本来用的是谷歌，一开始能进github，过了一会又说不是私密链接禁止了，只好先用360了

**Comment by user7314** [comment]
> > > > 是不是没有安装绳网跨域助手（一个跨域访问脚本）？
> > > 
> > > 
> > > 按教程应该我打开时它应该提示我的，但是浏览器直接说打不开网页
> > 
> > 
> > 截个图我看看
> 
> ![？](https://private-user-images.githubusercontent.com/178011582/356810676-3748acbb-7874-4258-bcbe-0de0802fbd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTI2MDQsIm5iZiI6MTcyMzI5MjMwNCwicGF0aCI6Ii8xNzgwMTE1ODIvMzU2ODEwNjc2LTM3NDhhY2JiLTc4NzQtNDI1OC1iY2JlLTBkZTA4MDJmYmQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxMjE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODQ4N2RkODJmNjUwMjJhOGZjN2M0ODQwY2NmNWRmODNjNmU0Y2RiMjJhZTEwM2VhZDg5YmFjYWM3NTdkNzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VWaEglNjZF3OWaJmi1dPozMs86eV1TvpW_joQ2pfEZQ) 本来是谷歌，一开始能进github，过了一会儿又说不是不再链接禁止了，只好先用360了

奇怪的是我把加速器关了就能进谷歌的github了，但还是不能进绳网链接

**Comment by Mayf1ower** [comment]
> > > > > 是不是没有安装绳网跨域助手（一个跨域访问脚本）？
> > > > 
> > > > 
> > > > 按教程应该我打开时它应该提示我的，但是浏览器直接说打不开网页
> > > 
> > > 
> > > 截个图我看看
> > 
> > 
> > ![？](https://private-user-images.githubusercontent.com/178011582/356810676-3748acbb-7874-4258-bcbe-0de0802fbd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTI2MDQsIm5iZiI6MTcyMzI5MjMwNCwicGF0aCI6Ii8xNzgwMTE1ODIvMzU2ODEwNjc2LTM3NDhhY2JiLTc4NzQtNDI1OC1iY2JlLTBkZTA4MDJmYmQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxMjE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODQ4N2RkODJmNjUwMjJhOGZjN2M0ODQwY2NmNWRmODNjNmU0Y2RiMjJhZTEwM2VhZDg5YmFjYWM3NTdkNzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VWaEglNjZF3OWaJmi1dPozMs86eV1TvpW_joQ2pfEZQ) 本来是谷歌，一开始能进github，过了一会儿又说不是不再链接禁止了，只好先用360了
> 
> 奇怪的是我把加速器关了就能进谷歌的github了，但还是不能进绳网链接

你用谷歌进一下绳网截个图我看看，截全屏

**Comment by user7314** [comment]
> > > > > > 是不是没有安装绳网跨域助手（一个跨域访问脚本）？
> > > > > 
> > > > > 
> > > > > 按教程应该我打开时它应该提示我的，但是浏览器直接说打不开网页
> > > > 
> > > > 
> > > > 截个图我看看
> > > 
> > > 
> > > ![？](https://private-user-images.githubusercontent.com/178011582/356810676-3748acbb-7874-4258-bcbe-0de0802fbd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTI2MDQsIm5iZiI6MTcyMzI5MjMwNCwicGF0aCI6Ii8xNzgwMTE1ODIvMzU2ODEwNjc2LTM3NDhhY2JiLTc4NzQtNDI1OC1iY2JlLTBkZTA4MDJmYmQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxMjE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODQ4N2RkODJmNjUwMjJhOGZjN2M0ODQwY2NmNWRmODNjNmU0Y2RiMjJhZTEwM2VhZDg5YmFjYWM3NTdkNzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VWaEglNjZF3OWaJmi1dPozMs86eV1TvpW_joQ2pfEZQ) 本来是谷歌，一开始能进github，过了一会儿又说不是不再链接禁止了，只好先用360了
> > 
> > 
> > 奇怪的是我把加速器关了就能进谷歌的github了，但还是不能进绳网链接
> 
> 你用谷歌进一下绳网截个图我看看，截全屏

![Uploading 666.png…]()

**Comment by user7314** [comment]
> > > > > > 是不是没有安装绳网跨域助手（一个跨域访问脚本）？
> > > > > 
> > > > > 
> > > > > 按教程应该我打开时它应该提示我的，但是浏览器直接说打不开网页
> > > > 
> > > > 
> > > > 截个图我看看
> > > 
> > > 
> > > ![？](https://private-user-images.githubusercontent.com/178011582/356810676-3748acbb-7874-4258-bcbe-0de0802fbd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTI2MDQsIm5iZiI6MTcyMzI5MjMwNCwicGF0aCI6Ii8xNzgwMTE1ODIvMzU2ODEwNjc2LTM3NDhhY2JiLTc4NzQtNDI1OC1iY2JlLTBkZTA4MDJmYmQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxMjE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODQ4N2RkODJmNjUwMjJhOGZjN2M0ODQwY2NmNWRmODNjNmU0Y2RiMjJhZTEwM2VhZDg5YmFjYWM3NTdkNzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VWaEglNjZF3OWaJmi1dPozMs86eV1TvpW_joQ2pfEZQ) 本来是谷歌，一开始能进github，过了一会儿又说不是不再链接禁止了，只好先用360了
> > 
> > 
> > 奇怪的是我把加速器关了就能进谷歌的github了，但还是不能进绳网链接
> 
> 你用谷歌进一下绳网截个图我看看，截全屏

![Uploading 666.png…]()

**Comment by user7314** [comment]
![Uploading 666.png…]()

**Comment by Mayf1ower** [comment]
你发的图片我看不到呀
你复制图片到文本框的时候等一会再发送，上传需要时间

**Comment by user7314** [comment]
![666](https://github.com/user-attachments/assets/284fee7b-2889-4722-a31e-58e68a114f51)

**Comment by user7314** [comment]
> 你发的图片我看不到呀 你复制图片到文本框的时候等一会再发送，上传需要时间

发了

**Comment by Mayf1ower** [comment]
这个网址你能上吗
https://share121.github.io/

**Comment by user7314** [comment]
> 这个网址你能上吗 https://share121.github.io/

不行，开不开加速器都不行

**Comment by InterKnotGuard** [comment]
可能是加速器没设置好？

> > 这个网址你能上吗 https://share121.github.io/
> 
> 不行，开不开加速器都不行

**Comment by user7314** [comment]
> 可能是加速器没设置好？
> 
> > > 这个网址你能上吗 https://share121.github.io/
> > 
> > 
> > 不行，开不开加速器都不行

不应该，关于github的选项我全开了

**Comment by user7314** [comment]
> > 可能是加速器没设置好？
> > > > 这个网址你能上吗 https://share121.github.io/
> > > 
> > > 
> > > 不行，开不开加速器都不行
> 
> 不应该，关于github的选项我全开了

突然可以开这个网址了，但是绳网的网址不行

**Comment by Mayf1ower** [comment]
> > > 可能是加速器没设置好？
> > > > > 这个网址你能上吗 https://share121.github.io/
> > > > 
> > > > 
> > > > 不行，开不开加速器都不行
> > 
> > 
> > 不应该，关于github的选项我全开了
> 
> 突然可以开这个网址了，但是绳网的网址不行

感觉像是DNS的问题啊
你试试看这个视频里的方法能不能解决
https://www.bilibili.com/video/BV1aF4m1K7EC/?spm_id_from=333.1365.top_right_bar_window_history.content.click&vd_source=c9d42f2f1a91c2b9992809794e10f36f

**Comment by user7314** [comment]
> > > > 可能是加速器没设置好？
> > > > > > 这个网址你能上吗 https://share121.github.io/
> > > > > 
> > > > > 
> > > > > 不行，开不开加速器都不行
> > > 
> > > 
> > > 不应该，关于github的选项我全开了
> > 
> > 
> > 突然可以开这个网址了，但是绳网的网址不行
> 
> 感觉像是DNS的问题啊 你试试看这个视频里的方法能不能解决 https://www.bilibili.com/video/BV1aF4m1K7EC/?spm_id_from=333.1365.top_right_bar_window_history.content.click&vd_source=c9d42f2f1a91c2b9992809794e10f36f

刷新出来了，感谢

**Comment by Mayf1ower** [comment]
不用谢~ 有帮到你就行(∠・ω< )⌒☆
