### ISSUE TITLE
[bug]帖子回复貌似只能显示100F，爱门贴现在已经没办法显示新的回复了

### ISSUE THREAD

**Issue by Mayf1ower** [share121/inter-knot#894]
![image](https://github.com/user-attachments/assets/b109346d-2353-4d8f-8761-6d2dd4f32ebc)

**Comment by capacitor1** [comment]
可能需要考虑性能。绳网有一个帖子说过，全都加载可能会对性能有影响🤔

但是我建议是增加一个选项，让用户可以选择显示多少 因为按这个规模发展，显示100还是太少了

**Comment by share121** [comment]
已支持无线滚动
