### ISSUE TITLE
教程再出出吧，外行很难进

### ISSUE THREAD

**Issue by GuY-sandtom** [share121/inter-knot#900]
ᐇ

**Comment by ssj20051003** [comment]
> > ᐇ
> 
> 要是出了教程，那红黄蓝绿都能进来了，本来就是要设立门槛，让污秽挡在门外，难一点才好，不然这里和某音有什么区别？

正确的中肯的一针见血的

**Comment by GuY-sandtom** [comment]
> > ᐇ
> 
> 要是出了教程，那红黄蓝绿都能进来了，本来就是要设立门槛，让污秽挡在门外，难一点才好，不然这里和某音有什么区别？

正确的

**Comment by TrafficLight6** [comment]
用英语写开发手册，这个方法行不行？

**Comment by huiye123-Hub** [comment]
我觉得这挺简单的呀？就花几分钟注册个账号就行了😃

**Comment by blhcm** [comment]
GitHub✅
Douyin❌

**Comment by CJYKK** [comment]
其实怎么感觉应该 close as Not Planned 呢（小声bb
