### ISSUE TITLE
[BUG]帖子左上角查看次数（随机数）失效了

### ISSUE THREAD

**Issue by InfinitumC** [share121/inter-knot#929]
每个帖子的查看次数都是977
这个数是有什么神秘含意吗？...

**Comment by TrafficLight6** [comment]
确实，我在[这儿](https://github.com/share121/inter-knot/issues/865)也提到了……
之前是随机的……

**Comment by TrafficLight6** [comment]
但是换个角度想，如果有人刷浏览量，会不会到时候又来一个java之父余胜军……

**Comment by InterKnotGuard** [comment]
哦修好了

**Comment by VacuolePaoo** [comment]
修复
